version: "3.3"

services:
  sogebot:
    image: docker.pkg.github.com/sogehige/sogebot/nightly:latest
    restart: always
    volumes:
      - ./conf:/app/conf/
      - ./shared:/app/shared/
    ports:
      - 20000:20000 # change your output port
    environment:
      # ensure locale exists in container, you may need to install it
      LANG: en_US.UTF-8

  adminer:
    image: adminer
    restart: always
    ports:
      - 20002:8080

