version: "3.3"

services:
  sogebot:
    # release
    image: docker.pkg.github.com/sogehige/sogebot/release:latest
    restart: always
    volumes:
      - ./shared:/app/shared/
    ports:
      - 20000:20000 # change your output port
    env_file:
      conf/.env
    environment:
      # ensure locale exists in container, you may need to install it
      LANG: en_US.UTF-8

  adminer:
    image: adminer
    restart: always
    ports:
      - 20001:8080

