version: "3.2"

services:
  sogebot:
    image: sogebot/nightly:latest
    restart: always
    volumes:
      - ./shared:/app/shared/
      - ./logs:/app/logs/
    ports:
      - 20000:20000 # change your output port
      #- 9229:9229 # uncomment to use --inspect port
    env_file:
      - ./conf/.env
    environment:
      # ensure locale exists in container, you may need to install it
      LANG: en_US.UTF-8
      #NODE_OPTIONS: --max_old_space_size=4096 # uncomment to set max 4GB RAM usage (default 2GB)
      #PROFILER: y # uncomment to enable --inspect

  ## Uncomment to install self-hosted dashboard available on port 12345
  #dashboard:
  #  container_name: sogeBot-Dashboard
  #  restart: always
  #  image: sogebot/dashboard:latest
  #  ports:
  #    - "12345:80"

  ## Uncomment to start dashboard autoupdater
  #watchtower:
  #  restart: always
  #  image: containrrr/watchtower
  #  container_name: watchtower
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  command: --interval 600 sogeBot-Dashboard

  ## Uncomment to install adminer
  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 20002:8080

